import { writeFileSync } from 'fs';
import * as path from 'path';
import * as prettier from 'prettier';
import { EntityMetadata } from 'typeorm';

import {
  entityListToImports,
  entityToOrderByEnum,
  entityToWhereArgs,
  entityToWhereInput,
  entityToWhereUniqueInput,
  entityToCreateInput,
  entityToUpdateInput,
  entityToUpdateInputArgs
} from './TypeORMConverter';

export class SchemaGenerator {
  static generate(
    entities: EntityMetadata[],
    destinationFolder: string,
    // This will reference 'warthog in the deployed module, but we need to do a relative import in the examples library
    warthogImportPath: string = 'warthog'
  ): string {
    let template = `
      // This file has been auto-generated by Warthog.  Do not update directly as it
      // will be re-written.  If you need to change this file, update models or add
      // new TypeGraphQL objects
      import { ArgsType, Field, InputType } from 'type-graphql';
      import { registerEnumType } from 'type-graphql';
      import { BaseWhereInput, PaginationArgs } from '${warthogImportPath}';
      ${entityListToImports(entities).join('')}
    `;

    entities.forEach((entity: EntityMetadata) => {
      template += `
        ${entityToOrderByEnum(entity)}
        ${entityToWhereInput(entity)}
        ${entityToWhereArgs(entity)}
        ${entityToWhereUniqueInput(entity)}
        ${entityToCreateInput(entity)}
        ${entityToUpdateInput(entity)}
        ${entityToUpdateInputArgs(entity)}
      `;
    });

    writeFileSync(path.join(destinationFolder, 'classes.ts'), format(template), {
      encoding: 'utf8',
      flag: 'w'
    });

    return template;
  }
}

function format(code: string, options: prettier.Options = {}) {
  try {
    // TODO: grab our prettier options (single quote, etc...)
    return prettier.format(code, {
      ...options,
      parser: 'typescript'
    });
  } catch (e) {
    console.log(`There is a syntax error in generated code, unformatted code printed, error: ${JSON.stringify(e)}`);
    return code;
  }
}
